---
launcher:
  a: "wezterm"
  f: "floorp"
  g: "feed-open"
  t: "trakt-progress"
  y: "mal-recent"
  d: "discord-browser"
  k: "keepassxc"
  b: "bookmark-open"
  l: "largechar-clipboard"
  x: "exo-web"
  "Shift+x": "exo-web-personal"
  n: "launch newsboat-force"
  m: "launch neomuttr"
  "Shift+m": "launch sync-neomutt"
  h: "launch htop"
  v: "launch keyvol"
  u: "urlview"
  p: "launch plainplay"
  "Shift+s": "launch splayall"
  s: "stream-corner"
  "$mod+f": "launch full_todotxt"
  4: "stream-corner-480"
  7: "stream-corner-720"
  0: "stream-corner-1080"
  "Shift+f": "flatpak-run"
  c: "clrs"
  "Shift+n": "launch sn"
  "$mod+c": "SKIP_RECENT=1 launch cz"
  "Shift+c": "SKIP_RECENT=1 launch czd"
  "$alt+c": "SKIP_RECENT=1 launch czl"
workspaces:
  1: 1
  2: 2
  3: 3
  4: 4
  5: 5
  6: 6
  7: 7
  8: 8
  9: 9
  0: 10
