["https://update.greasyfork.org/scripts/540055/YouTube%20Tweaker%20Pro%20%28Full%20Suite%29%20%5Bv335%20Aggressive%20Ads%20%2B%20SponsorBlock%20%2B%20Pre-roll%20Sniper%5D.user.js"]
url = "https://update.greasyfork.org/scripts/540055/YouTube%20Tweaker%20Pro%20%28Full%20Suite%29%20%5Bv335%20Aggressive%20Ads%20%2B%20SponsorBlock%20%2B%20Pre-roll%20Sniper%5D.user.js"
nickname = "youtube tweaks"
pinned = false
last_updated = 1767487007
needs_update = true
